/**
 * Setup Git Hooks
 * Installs pre-commit hook for spec compliance checks
 *
 * Runs automatically via `pnpm install` (prepare script)
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const HOOKS_DIR = path.join(ROOT, '.git', 'hooks');
const HOOK_PATH = path.join(HOOKS_DIR, 'pre-commit');

const HOOK_CONTENT = `#!/bin/sh
# Auto-generated by scripts/setup-hooks.ts
# Run spec compliance checks before commit

cd "$(git rev-parse --show-toplevel)"
pnpm check:spec
`;

// Only setup if .git exists (not in CI or npm publish)
if (fs.existsSync(path.join(ROOT, '.git'))) {
  fs.mkdirSync(HOOKS_DIR, { recursive: true });
  fs.writeFileSync(HOOK_PATH, HOOK_CONTENT, { mode: 0o755 });
  console.log('Git pre-commit hook installed');
}
